# Generated by Django 5.0.4 on 2025-03-08 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=25)),
                ('dep_des', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name': 'Departments',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=25)),
                ('doc_pic', models.ImageField(upload_to='doctors/')),
                ('doc_face_book', models.URLField(blank=True, null=True)),
                ('doc_twitter', models.URLField(blank=True, null=True)),
                ('doc_insta', models.URLField(blank=True, null=True)),
                ('doc_dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.department')),
            ],
            options={
                'verbose_name': 'Doctors',
                'verbose_name_plural': 'Doctors',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('booked', models.DateField()),
                ('time', models.TimeField()),
                ('desc', models.TextField(max_length=500)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.doctor')),
            ],
            options={
                'verbose_name': 'Bookings',
                'verbose_name_plural': 'Bookings',
            },
        ),
    ]
