# Generated by Django 5.0.4 on 2025-03-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_name', models.CharField(max_length=25)),
                ('cus_job', models.CharField(max_length=50)),
                ('cus_desc', models.TextField(max_length=500)),
                ('cus_pic', models.ImageField(upload_to='customer_pic/')),
            ],
            options={
                'verbose_name': 'feedbacks',
                'verbose_name_plural': 'feedbacks',
            },
        ),
    ]
