# Generated by Django 5.0.4 on 2025-03-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('desc', models.CharField(max_length=500)),
                ('blog_pic', models.ImageField(upload_to='blog/')),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'Blogs',
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
