# Generated by Django 5.0.4 on 2025-03-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='message',
            field=models.CharField(max_length=300),
        ),
    ]
