# Generated by Django 5.0.4 on 2025-03-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_support_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='message',
            field=models.CharField(max_length=100),
        ),
    ]
