# Generated by Django 5.0.4 on 2025-03-15 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='pic',
            field=models.ImageField(default=2, upload_to='patient_pic/'),
            preserve_default=False,
        ),
    ]
