# Generated by Django 5.0.4 on 2025-03-15 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_patient_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='disease',
            field=models.FileField(max_length=50, upload_to=''),
        ),
    ]
